/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Merch Shop Products & Orders
 * A full list of all routes for the T&T Merch Shop
 * OpenAPI spec version: 1.0
 */
import { customInstance } from "./axiosInstance";
import type { BodyType } from "./axiosInstance";
export interface ProductDTO {
  name: string;
  /** @nullable */
  description: string | null;
  id: string;
}

export interface ProductListDTO {
  items: ProductDTO[];
  totalCount: number;
}

export interface CreateOrderItemDTO {
  productId: string;
  /** @minItems 1 */
  productVariantId: string[];
  /** @minimum 1 */
  quantity: number;
}

export interface CreateOrderDTO {
  userId: string;
  /** @minItems 1 */
  items: CreateOrderItemDTO[];
}

export interface OrderItemVariantDTO {
  id: string;
  productVariantId: string;
  category: string;
  name: string;
  description: string;
}

export interface OrderItemDTO {
  id: string;
  orderId: string;
  productId: string;
  name: string;
  /** @minimum 1 */
  quantity: number;
  productVariants: OrderItemVariantDTO[];
}

export interface OrderDTO {
  id: string;
  userId: string;
  /** @minItems 1 */
  items: OrderItemDTO[];
}

export interface ProductVariantCategoriesDTO {
  categories: string[];
}

export interface ProductVariantOutgoingDTO {
  category: string;
  name: string;
  productVariantId: string;
}

export interface ProductVariantListDTO {
  items: ProductVariantOutgoingDTO[];
}

export type ProductVariantControllerFindVariantsParams = {
  category?: string;
};

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

export const productsControllerFindAll = (
  options?: SecondParameter<typeof customInstance<ProductListDTO>>,
) => {
  return customInstance<ProductListDTO>(
    { url: `/product`, method: "GET" },
    options,
  );
};

export const orderControllerCreate = (
  createOrderDTO: BodyType<CreateOrderDTO>,
  options?: SecondParameter<typeof customInstance<OrderDTO>>,
) => {
  return customInstance<OrderDTO>(
    {
      url: `/orders`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: createOrderDTO,
    },
    options,
  );
};

export const productVariantCategoryControllerFindCategories = (
  productId: string,
  options?: SecondParameter<typeof customInstance<ProductVariantCategoriesDTO>>,
) => {
  return customInstance<ProductVariantCategoriesDTO>(
    { url: `/product/${productId}/category`, method: "GET" },
    options,
  );
};

export const productVariantControllerFindVariants = (
  productId: string,
  params?: ProductVariantControllerFindVariantsParams,
  options?: SecondParameter<typeof customInstance<ProductVariantListDTO>>,
) => {
  return customInstance<ProductVariantListDTO>(
    { url: `/product/${productId}/variant`, method: "GET", params },
    options,
  );
};

export type ProductsControllerFindAllResult = NonNullable<
  Awaited<ReturnType<typeof productsControllerFindAll>>
>;
export type OrderControllerCreateResult = NonNullable<
  Awaited<ReturnType<typeof orderControllerCreate>>
>;
export type ProductVariantCategoryControllerFindCategoriesResult = NonNullable<
  Awaited<ReturnType<typeof productVariantCategoryControllerFindCategories>>
>;
export type ProductVariantControllerFindVariantsResult = NonNullable<
  Awaited<ReturnType<typeof productVariantControllerFindVariants>>
>;
